version: '3.8'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  dotnet_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis