// <auto-generated />
using System;
using HospitalManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240326091455_removes-many-to-many-relation-between-job-and-department")]
    partial class removesmanytomanyrelationbetweenjobanddepartment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppUserRole", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AppUserRole");
                });

            modelBuilder.Entity("HospitalManagement.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("HospitalManagement.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0169dd27-a25a-46d7-91c5-5c24e0a5fd54"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(991),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(993),
                            IsDeleted = false,
                            Name = "EMERGENCY DEPARTMENT"
                        },
                        new
                        {
                            Id = new Guid("6bfb6b7e-2091-4a82-a7a9-f14df1a92450"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1007),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1008),
                            IsDeleted = false,
                            Name = "MEDICAL/SURGICAL UNIT"
                        },
                        new
                        {
                            Id = new Guid("9bfc8c5c-5906-4a44-96ae-71f17e22e7e1"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1011),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1011),
                            IsDeleted = false,
                            Name = "INTENSIVE CARE UNIT"
                        },
                        new
                        {
                            Id = new Guid("b60d76e9-5cc5-44e7-9336-18e45494ff26"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1012),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1012),
                            IsDeleted = false,
                            Name = "LABORATORY"
                        },
                        new
                        {
                            Id = new Guid("5a128d7e-c137-47b1-bd49-2e9733d694ad"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1013),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1014),
                            IsDeleted = false,
                            Name = "RADIOLOGY"
                        },
                        new
                        {
                            Id = new Guid("1aae1f9e-3a45-4ee6-8b3d-f86b2b73b3f9"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1015),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1015),
                            IsDeleted = false,
                            Name = "PHARMACY"
                        },
                        new
                        {
                            Id = new Guid("7b7f70f0-414c-4b25-8602-3e005aeb5869"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1017),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1017),
                            IsDeleted = false,
                            Name = "OPERATING ROOMS"
                        },
                        new
                        {
                            Id = new Guid("a15b0843-2c4d-4bcb-bc88-028e14e6cb69"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1018),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1018),
                            IsDeleted = false,
                            Name = "MATERNITY/WOMEN'S HEALTH"
                        },
                        new
                        {
                            Id = new Guid("02b204b2-ee02-4a25-b087-d21e7cb9abf3"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1019),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1020),
                            IsDeleted = false,
                            Name = "PEDIATRICS"
                        },
                        new
                        {
                            Id = new Guid("fbd52b17-d1b5-44f2-bdc0-af2d749150bf"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1021),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1021),
                            IsDeleted = false,
                            Name = "PSYCHIATRY/PSYCHOLOGY"
                        },
                        new
                        {
                            Id = new Guid("dc06a832-8d7c-42b6-a5c8-177c15dc52ff"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1022),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1022),
                            IsDeleted = false,
                            Name = "PHYSICAL THERAPY/REHABILITATION"
                        },
                        new
                        {
                            Id = new Guid("bf92ad4f-ebae-4e1f-97e4-9f61adba017b"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1023),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1024),
                            IsDeleted = false,
                            Name = "NUTRITION SERVICES"
                        },
                        new
                        {
                            Id = new Guid("2b23f10a-9319-4862-856f-6fca2c64a5f3"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1025),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1025),
                            IsDeleted = false,
                            Name = "RESPIRATORY THERAPY"
                        },
                        new
                        {
                            Id = new Guid("f9a0b47f-8c2c-43dc-9e19-7d963f7f7d43"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1026),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1026),
                            IsDeleted = false,
                            Name = "SOCIAL SERVICES"
                        },
                        new
                        {
                            Id = new Guid("d5f66dc4-dfad-4be0-90a3-251a97ad9462"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1027),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1028),
                            IsDeleted = false,
                            Name = "ADMINISTRATION/MANAGEMENT"
                        });
                });

            modelBuilder.Entity("HospitalManagement.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("HospitalManagement.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genotype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HospitalManagement.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f10c02a-fa84-4936-837d-afa77e5bb238"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1464),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1464),
                            IsDeleted = false,
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("607fbfc9-b509-48b9-acd0-dcfdcda51daa"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1467),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1468),
                            IsDeleted = false,
                            Name = "SUPERADMIN"
                        },
                        new
                        {
                            Id = new Guid("409dfa54-8822-41fc-8f93-f2a31378e436"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1469),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1469),
                            IsDeleted = false,
                            Name = "STAFF"
                        },
                        new
                        {
                            Id = new Guid("0169dd27-a25a-46d7-91c5-5c24e0a5fd54"),
                            CreatedBy = "ADMIN",
                            DateCreated = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1471),
                            DateModified = new DateTime(2024, 3, 26, 9, 14, 54, 730, DateTimeKind.Utc).AddTicks(1471),
                            IsDeleted = false,
                            Name = "PATIENT"
                        });
                });

            modelBuilder.Entity("HospitalManagement.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("StaffID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("AppUserRole", b =>
                {
                    b.HasOne("HospitalManagement.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagement.Domain.Entities.Job", b =>
                {
                    b.HasOne("HospitalManagement.Domain.Entities.Department", "Department")
                        .WithMany("Job")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HospitalManagement.Domain.Entities.Patient", b =>
                {
                    b.HasOne("HospitalManagement.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("HospitalManagement.Domain.Entities.Staff", b =>
                {
                    b.HasOne("HospitalManagement.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HospitalManagement.Domain.Entities.Department", b =>
                {
                    b.Navigation("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
